//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wagharalkar.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WagharalkarEntities : DbContext
    {
        public WagharalkarEntities()
            : base("name=WagharalkarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblActivity> tblActivities { get; set; }
        public virtual DbSet<tblAppoinment> tblAppoinments { get; set; }
        public virtual DbSet<tblAward> tblAwards { get; set; }
        public virtual DbSet<tblPhotoGallery> tblPhotoGalleries { get; set; }
        public virtual DbSet<tblVideoGallery> tblVideoGalleries { get; set; }
    }
}
